#!/usr/bin/env python3
"""Discover */main.c, compile each with Emscripten+SDL3, generate the gallery."""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
DIST = ROOT / "dist"
WINDOW_TITLE = re.compile(r'SDL_CreateWindow\(\s*"([^"]*)"', re.S)


def discover() -> list[dict]:
    effects = []
    for src in sorted(ROOT.glob("*/main.c")):
        folder = src.parent.name
        if folder in {"web", "docs", "dist"}:
            continue
        text = src.read_text(encoding="utf-8", errors="replace")
        match = WINDOW_TITLE.search(text)
        title = match.group(1).strip() if match else folder.replace("_", " ").title()
        effects.append(
            {
                "id": folder,
                "title": title,
                "src": src,
            }
        )
    if not effects:
        sys.exit("No */main.c demos found.")
    return effects


def require_emcc() -> str:
    emcc = shutil.which("emcc")
    if not emcc:
        sys.exit("emcc not found. Install Emscripten and source emsdk_env.sh.")
    return emcc


def compile_one(emcc: str, effect: dict) -> None:
    out_dir = DIST / effect["id"]
    out_dir.mkdir(parents=True, exist_ok=True)
    shell = WEB / "shell.html"
    cmd = [
        emcc,
        str(effect["src"]),
        "-O2",
        "-sUSE_SDL=3",
        "-sASYNCIFY=1",
        "-sASYNCIFY_STACK_SIZE=16384",
        "-sALLOW_MEMORY_GROWTH=1",
        "-sINITIAL_MEMORY=33554432",
        "-sSTACK_SIZE=1048576",
        "-sENVIRONMENT=web",
        f"--shell-file={shell}",
        "-o",
        str(out_dir / "index.html"),
    ]
    print(f"emcc {effect['id']}", flush=True)
    subprocess.run(cmd, check=True, cwd=ROOT)
    html_path = out_dir / "index.html"
    html = html_path.read_text(encoding="utf-8")
    html = html.replace("<title>Math Game Effects</title>", f"<title>{effect['title']}</title>")
    html = html.replace(">Demo</h1>", f">{effect['title']}</h1>")
    html_path.write_text(html, encoding="utf-8")
    shutil.copyfile(WEB / "style.css", out_dir / "style.css")


def write_index(effects: list[dict]) -> None:
    cards = "\n".join(
        f"""      <a class="card" href="./{e['id']}/">
        <h2>{e['title']}</h2>
        <p>Compiled from <code>{e['id']}/main.c</code></p>
        <span class="tag">{e['id']}</span>
      </a>"""
        for e in effects
    )
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Math Game Effects</title>
  <link rel="stylesheet" href="./style.css" />
</head>
<body>
  <div class="wrap">
    <header class="site-header">
      <p class="kicker">{len(effects)} demos · generated by GitHub Actions</p>
      <h1>Math Game Effects</h1>
      <p class="lede">
        Each page is the original C + SDL3 demo compiled to WebAssembly with Emscripten.
        New folders with <code>main.c</code> are picked up automatically on the next build.
        <a href="https://github.com/humbertodias/math-game-effects">Source on GitHub</a>
      </p>
    </header>
    <main class="gallery">
{cards}
    </main>
    <footer class="site-footer">
      <p>Built from the C sources · ESC quits a demo · gallery link to go back</p>
    </footer>
  </div>
</body>
</html>
"""
    (DIST / "index.html").write_text(html, encoding="utf-8")
    shutil.copyfile(WEB / "style.css", DIST / "style.css")
    (DIST / ".nojekyll").write_text("", encoding="utf-8")


def main() -> None:
    emcc = require_emcc()
    effects = discover()
    print(f"Found {len(effects)} demos", flush=True)

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()

    print("Building SDL3 port (first run may take a few minutes)…", flush=True)
    port = subprocess.run(["embuilder", "build", "sdl3"], cwd=ROOT)
    pending = effects
    if port.returncode != 0:
        print("embuilder could not prebuild sdl3; compiling one demo first", flush=True)
        compile_one(emcc, effects[0])
        pending = effects[1:]

    jobs = max(1, min(4, os.cpu_count() or 2))
    failures = []
    with ThreadPoolExecutor(max_workers=jobs) as pool:
        futures = {pool.submit(compile_one, emcc, effect): effect for effect in pending}
        for fut in as_completed(futures):
            effect = futures[fut]
            try:
                fut.result()
            except subprocess.CalledProcessError as exc:
                failures.append(f"{effect['id']}: exit {exc.returncode}")

    if failures:
        sys.exit("Compile failed:\n  " + "\n  ".join(failures))

    write_index(effects)
    print(f"Wrote gallery with {len(effects)} demos → {DIST}", flush=True)


if __name__ == "__main__":
    main()
